[package]
name = "mdbook"
version = "0.0.3"
authors = ["Mathieu David <mathieudavid@mathieudavid.org>"]
description = "create books from markdown files (like Gitbook)"
documentation = "http://azerupi.github.io/mdBook/index.html"
repository = "https://github.com/azerupi/mdBook"
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
readme = "README.md"
build = "build.rs"
exclude = [
    "book-example/*",
]

[dependencies]
clap = "~1.5.3"
handlebars = "=0.11.2"
rustc-serialize = "~0.3.16"
pulldown-cmark = "~0.0.3"

[dev-dependencies]
tempdir = "~0.3.4"

[features]
default = ["output"]
debug = []
output = []
regenerate-css = []

[[bin]]
doc = false
name = "mdbook"
path = "src/bin/mdbook.rs"
