[package]
name = "mdbook"
version = "0.0.1"
authors = ["Mathieu David <mathieudavid@mathieudavid.org>"]
description = "create books from markdown files (like Gitbook)"
documentation = "http://azerupi.github.io/mdBook/index.html"
repository = "https://github.com/azerupi/mdBook"
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL"
readme = "README.md"
exclude = [
    "book-example/*",
]

[dependencies]
clap = "*"
handlebars = "*"
rustc-serialize = "*"
pulldown-cmark = "*"

[dev-dependencies]
tempdir = "*"

[features]
default = ["output"]
debug = []
output = []

[[bin]]
doc = false
name = "mdbook"
path = "src/bin/mdbook.rs"
